### ISSUE TITLE
Huge Cavern never loads in properly

### ISSUE THREAD

**Issue by teagan75** [kegare/Cavern-Miner#11]
After entering the huge cavern or starting there as caveborn, my internal server freezes forever and all i can do is walk around

if i try to quit it says saving world forever until i used task manager

 It is only the Huge Cavern that has this issue. Nothing in the log. No crash report. Taking the view distance down does not help.

**Comment by gamax92** [comment]
If `VeinFeature.getPositions()` is unable to retrieve `vein.getCount()` number of unique valid positions for some reason, in my case `targetY` was always empty and thus there were no valid positions, then it will loop forever looking for a position and hang the server.

The limit either needs to be placed before the `BlockPos.ZERO` filter or an additional limit should be placed in order to ensure the loop stops hanging. I just added a second `.limit(100)` before the filter and now the cavern stops hanging.

Also this can happen on the normal cavern as well, though much less frequently.

**Comment by kegare** [comment]
This critical issue was fixed now!
Thanks a lot, teagan75 and gamax92.

**Comment by teagan75** [comment]
FYI your update wiped out my config changes. Luckily I had a backup
